import type { DefaultTheme } from 'vitepress'

const sidebar: DefaultTheme.Sidebar = [
  {
    text: 'Categories',
    items: [
      { text: 'Overview', link: '/categories/overview' },
      {
        text: 'Interview Questions',
        link: '/categories/interview-questions/overview',
        collapsed: true,
        items: [
          { text: 'Initial Access', link: '/categories/interview-questions/overview#initial-access' },
          { text: 'Windows Network', link: '/categories/interview-questions/overview#windows-network' },
          { text: 'Active Directory', link: '/categories/interview-questions/overview#active-directory' },
          { text: 'OS Language Programming', link: '/categories/interview-questions/overview#os-language-programming' },
          { text: 'PowerShell', link: '/categories/interview-questions/overview#powershell' },
          { text: 'Windows Internals', link: '/categories/interview-questions/overview#windows-internals' },
          { text: 'DNS Server', link: '/categories/interview-questions/overview#dns-server' },
          { text: 'Windows API', link: '/categories/interview-questions/overview#windows-api' },
          { text: 'Macro Attack', link: '/categories/interview-questions/overview#macro-attack' },
          { text: 'APT Groups', link: '/categories/interview-questions/overview#apt-groups' },
          { text: 'EDR and Antivirus', link: '/categories/interview-questions/overview#edr-and-antivirus' },
          { text: 'Malware Development', link: '/categories/interview-questions/overview#malware-development' },
          { text: 'System & Kernel Programming', link: '/categories/interview-questions/overview#system-kernel-programming' },
          { text: 'Privilege Escalation', link: '/categories/interview-questions/overview#privilege-escalation' },
          { text: 'Post-exploitation (and Lateral Movement)', link: '/categories/interview-questions/overview#post-exploitation-and-lateral-movement' },
          { text: 'Persistence', link: '/categories/interview-questions/overview#persistence' },
          { text: 'Breaking Hash', link: '/categories/interview-questions/overview#breaking-hash' },
          { text: 'C&C (Command and Control)', link: '/categories/interview-questions/overview#cc-command-and-control' },
          { text: 'DLL', link: '/categories/interview-questions/overview#dll' },
          { text: 'DNS Rebinding', link: '/categories/interview-questions/overview#dns-rebinding' },
          { text: 'LDAP', link: '/categories/interview-questions/overview#ldap' },
          { text: 'Evasion', link: '/categories/interview-questions/overview#evasion' },
          { text: 'Steganography', link: '/categories/interview-questions/overview#steganography' },
          { text: 'Kerberoasting and Kerberos', link: '/categories/interview-questions/overview#kerberoasting-and-kerberos' },
          { text: 'Mimikatz', link: '/categories/interview-questions/overview#mimikatz' },
          { text: 'RDP', link: '/categories/interview-questions/overview#rdp' },
          { text: 'NTLM', link: '/categories/interview-questions/overview#ntlm' },
          { text: 'YARA Language', link: '/categories/interview-questions/overview#yara-language' },
          { text: 'Windows API And DLL Difference', link: '/categories/interview-questions/overview#windows-api-and-dll-difference' },
          { text: 'Antivirus and EDR Difference', link: '/categories/interview-questions/overview#antivirus-and-edr-difference' },
          { text: 'NTDLL', link: '/categories/interview-questions/overview#ntdll' },
          { text: 'Native API', link: '/categories/interview-questions/overview#native-api' },
          { text: 'Windows Driver', link: '/categories/interview-questions/overview#windows-driver' },
          { text: 'Tunneling', link: '/categories/interview-questions/overview#tunneling' },
          { text: 'Shadow File', link: '/categories/interview-questions/overview#shadow-file' },
          { text: 'SAM File', link: '/categories/interview-questions/overview#sam-file' },
          { text: 'LSA', link: '/categories/interview-questions/overview#lsa' },
          { text: 'LSASS', link: '/categories/interview-questions/overview#lsass' },
          { text: 'WDIGEST', link: '/categories/interview-questions/overview#wdigest' },
          { text: 'CredSSP', link: '/categories/interview-questions/overview#credssp' },
          { text: 'MSV', link: '/categories/interview-questions/overview#msv' },
          { text: 'LiveSSP', link: '/categories/interview-questions/overview#livessp' },
          { text: 'TSpkg', link: '/categories/interview-questions/overview#tspkg' },
          { text: 'CredMan', link: '/categories/interview-questions/overview#credman' },
          { text: 'EDR NDR XDR', link: '/categories/interview-questions/overview#edr-ndr-xdr' },
          { text: 'Polymorphic Malware', link: '/categories/interview-questions/overview#polymorphic-malware' },
          { text: 'Pass-the-Hash, Pass-the-Ticket or Build Golden Tickets', link: '/categories/interview-questions/overview#pass-the-hash-pass-the-ticket-or-build-golden-tickets' },
          { text: 'Firewall', link: '/categories/interview-questions/overview#firewall' },
          { text: 'WinDBG (Windows Debugger)', link: '/categories/interview-questions/overview#windbg-windows-debugger' },
          { text: 'PE (Portable Executable)', link: '/categories/interview-questions/overview#pe-portable-executable' },
          { text: 'ICMP', link: '/categories/interview-questions/overview#icmp' },
          { text: 'Major Microsoft frameworks for Windows', link: '/categories/interview-questions/overview#major-microsoft-frameworks-for-windows' },
          { text: 'Services and Processes', link: '/categories/interview-questions/overview#services-and-processes' },
          { text: 'svchost', link: '/categories/interview-questions/overview#svchost' },
          { text: 'CIM Class', link: '/categories/interview-questions/overview#cim-class' },
          { text: 'CDB, NTSD, KD, Gflags, GflagsX, PE Explorer', link: '/categories/interview-questions/overview#cdb-ntsd-kd-gflags-gflagsx-pe-explorer' },
          { text: 'Sysinternals Suite (tools)', link: '/categories/interview-questions/overview#sysinternals-suite-tools' },
          { text: 'Undocumented Functions', link: '/categories/interview-questions/overview#undocumented-functions' },
          { text: 'Process Explorer vs Process Hacker', link: '/categories/interview-questions/overview#process-explorer-vs-process-hacker' },
          { text: 'CLR (Common Language Runtime)', link: '/categories/interview-questions/overview#clr-common-language-runtime' },
        ],
      },
      {
        text: 'Ethical Hacking Labs',
        collapsed: true,
        items: [
          {
            text: '0 - Core Knowledge',
            collapsed: true,
            items: [
              { text: 'Networking 101', link: '/categories/ethical-hacking-labs/0-core-knowledge/0-Networking-101' },
              { text: 'Lab Building', link: '/categories/ethical-hacking-labs/0-core-knowledge/1-Lab-Building' },
              { text: 'Intro to Linux', link: '/categories/ethical-hacking-labs/0-core-knowledge/2-Intro-to-Linux' },
              { text: 'Infosec 101', link: '/categories/ethical-hacking-labs/0-core-knowledge/4-Infosec-101' },
            ],
          },
          {
            text: '1 - Footprinting & Reconnaissance',
            collapsed: true,
            items: [
              { text: 'What is Footprinting', link: '/categories/ethical-hacking-labs/1-footprinting-and-reconnaissance/0-What-is-Footprinting' },
              { text: 'Windows CommandLine', link: '/categories/ethical-hacking-labs/1-footprinting-and-reconnaissance/1-Windows-CommandLine' },
              { text: 'Maltego Basics', link: '/categories/ethical-hacking-labs/1-footprinting-and-reconnaissance/2-Maltego-Basics' },
              { text: 'Recon-ng', link: '/categories/ethical-hacking-labs/1-footprinting-and-reconnaissance/3-Recon-ng' },
              { text: 'OSRFramework', link: '/categories/ethical-hacking-labs/1-footprinting-and-reconnaissance/4-OSRFramework' },
              { text: 'Metasploit Basics', link: '/categories/ethical-hacking-labs/1-footprinting-and-reconnaissance/5-Metasploit-Basics' },
              { text: 'theHarvester', link: '/categories/ethical-hacking-labs/1-footprinting-and-reconnaissance/6-theHarvester' },
              { text: 'Other Tools', link: '/categories/ethical-hacking-labs/1-footprinting-and-reconnaissance/7-Other-Tools' },
            ],
          },
          {
            text: '2 - Scanning Networks',
            collapsed: true,
            items: [
              { text: 'Scanning a Target Network', link: '/categories/ethical-hacking-labs/2-scanning-networks/0-Scanning-a-Target-Network' },
              { text: 'hping3', link: '/categories/ethical-hacking-labs/2-scanning-networks/1-hping3' },
              { text: 'TTL Detection', link: '/categories/ethical-hacking-labs/2-scanning-networks/2-TTL' },
              { text: 'MegaPing', link: '/categories/ethical-hacking-labs/2-scanning-networks/3-MegaPing' },
              { text: 'Nmap', link: '/categories/ethical-hacking-labs/2-scanning-networks/4-Nmap' },
              { text: 'Nmap Decoy IP', link: '/categories/ethical-hacking-labs/2-scanning-networks/5-NmapDecoyIP' },
              { text: 'Windows Tools', link: '/categories/ethical-hacking-labs/2-scanning-networks/6-WindowsTools' },
            ],
          },
          {
            text: '3 - Enumeration',
            collapsed: true,
            items: [
              { text: 'Introduction', link: '/categories/ethical-hacking-labs/3-enumeration/0-Introduction' },
              { text: 'Enumerating with Nmap', link: '/categories/ethical-hacking-labs/3-enumeration/1-Enumerating-with-Nmap' },
              { text: 'SNMP Enumeration', link: '/categories/ethical-hacking-labs/3-enumeration/2-SNMP-Enumeration' },
              { text: 'Enum4Linux', link: '/categories/ethical-hacking-labs/3-enumeration/3-Enum4linux-Win-and-Samba-Enumeration' },
              { text: 'Windows Enumeration Tools', link: '/categories/ethical-hacking-labs/3-enumeration/4-Windows-EnumerationTools' },
            ],
          },
          {
            text: '4 - Vulnerability Analysis',
            collapsed: true,
            items: [
              { text: 'Overview and Tools', link: '/categories/ethical-hacking-labs/4-vulnerability-analysis/Overview-and-Tools' },
            ],
          },
          {
            text: '5 - System Hacking',
            collapsed: true,
            items: [
              { text: 'Introduction', link: '/categories/ethical-hacking-labs/5-system-hacking/0-Introduction' },
              { text: 'LLMNR / NBT-NS Spoofing', link: '/categories/ethical-hacking-labs/5-system-hacking/1-LLMNR-NBT-NS' },
              { text: 'SAM Hashes', link: '/categories/ethical-hacking-labs/5-system-hacking/2-SAM-Hashes' },
              { text: 'Rainbow Tables', link: '/categories/ethical-hacking-labs/5-system-hacking/3-Rainbow-tables' },
              { text: 'VNC Session', link: '/categories/ethical-hacking-labs/5-system-hacking/4-VNC-Session' },
              { text: 'Escalating Privileges', link: '/categories/ethical-hacking-labs/5-system-hacking/5-Escalating-Privileges' },
              { text: 'Hacking with Doc File', link: '/categories/ethical-hacking-labs/5-system-hacking/6-Hacking-Windows-with-Doc-file' },
              { text: 'Metasploit Post-Exploitation', link: '/categories/ethical-hacking-labs/5-system-hacking/7-Hacking-Windows-with-Metasploit-PostExploitation' },
              { text: 'NTFS Streams', link: '/categories/ethical-hacking-labs/5-system-hacking/8-NTFS-Streams' },
              { text: 'Steganography', link: '/categories/ethical-hacking-labs/5-system-hacking/9-Steganography' },
              { text: 'Covert TCP', link: '/categories/ethical-hacking-labs/5-system-hacking/10-Covert_TCP' },
              { text: 'Auditpol', link: '/categories/ethical-hacking-labs/5-system-hacking/11-Auditpol' },
              { text: 'Windows Tools', link: '/categories/ethical-hacking-labs/5-system-hacking/12-WindowsTools' },
            ],
          },
          {
            text: '6 - Malware',
            collapsed: true,
            items: [
              { text: 'Introduction', link: '/categories/ethical-hacking-labs/6-malware/0-Introduction' },
              { text: 'njRAT', link: '/categories/ethical-hacking-labs/6-malware/1-Using-njRAT' },
              { text: 'HTTP RAT Trojan', link: '/categories/ethical-hacking-labs/6-malware/2-HTTP-Trojan' },
              { text: 'Obfuscating Trojan', link: '/categories/ethical-hacking-labs/6-malware/3-Obfuscating-Trojan-SwayzCryptor' },
              { text: 'Malware Analysis Lab', link: '/categories/ethical-hacking-labs/6-malware/4-Malware-Analysis-Lab' },
              { text: 'Windows Tools', link: '/categories/ethical-hacking-labs/6-malware/5-Windows-Tools' },
            ],
          },
          {
            text: '7 - Sniffing',
            collapsed: true,
            items: [
              { text: 'Introduction', link: '/categories/ethical-hacking-labs/7-sniffing/0-Introduction' },
              { text: 'MITM with BetterCAP', link: '/categories/ethical-hacking-labs/7-sniffing/1-MITM-with-Bettercap' },
              { text: 'MAC Address Spoofing', link: '/categories/ethical-hacking-labs/7-sniffing/2-Spoofing-MAC-address' },
              { text: 'Windows Tools', link: '/categories/ethical-hacking-labs/7-sniffing/X-Windows-Tools' },
            ],
          },
          {
            text: '8 - Social Engineering',
            collapsed: true,
            items: [
              { text: 'Introduction', link: '/categories/ethical-hacking-labs/8-social-engineering/0-Introduction' },
              { text: 'Using SET', link: '/categories/ethical-hacking-labs/8-social-engineering/1-Using-SET' },
              { text: 'Tools', link: '/categories/ethical-hacking-labs/8-social-engineering/X-Tools' },
            ],
          },
          {
            text: '9 - Denial of Service',
            collapsed: true,
            items: [
              { text: 'Introduction', link: '/categories/ethical-hacking-labs/9-denial-of-service/0-Introduction' },
              { text: 'SYN Flooding', link: '/categories/ethical-hacking-labs/9-denial-of-service/1-SYN-Flooding' },
              { text: 'DDoS with HOIC', link: '/categories/ethical-hacking-labs/9-denial-of-service/2-DDoS-using-HOIC' },
              { text: 'Detecting DoS Traffic', link: '/categories/ethical-hacking-labs/9-denial-of-service/3-Detecting-DoS-Traffic' },
            ],
          },
          {
            text: '10 - Session Hijacking',
            collapsed: true,
            items: [
              { text: 'Introduction', link: '/categories/ethical-hacking-labs/10-session-hijacking/0-Introduction' },
              { text: 'Using ZAP', link: '/categories/ethical-hacking-labs/10-session-hijacking/1-Using-ZAP' },
              { text: 'Intercepting HTTP Traffic', link: '/categories/ethical-hacking-labs/10-session-hijacking/2-Intercepting-HTTP-Traffic' },
            ],
          },
          {
            text: '11 - Bonus (Forensics)',
            collapsed: true,
            items: [
              { text: 'TCPDump', link: '/categories/ethical-hacking-labs/11-bonus/TCPDump-Tutorial' },
              { text: 'Dissecting Packets', link: '/categories/ethical-hacking-labs/11-bonus/Dissecting-packets' },
              { text: 'ExifTool', link: '/categories/ethical-hacking-labs/11-bonus/ExifTool-Tutorial' },
              { text: 'hdparm & dd', link: '/categories/ethical-hacking-labs/11-bonus/Using-hdparm-and-dd-command' },
              { text: 'Recovering Deleted Partition', link: '/categories/ethical-hacking-labs/11-bonus/Recovering-Deleted-Partition' },
              { text: 'Recovering Deleted Files', link: '/categories/ethical-hacking-labs/11-bonus/Recovering-Deleted-Files' },
            ],
          },
        ],
      },
    ],
  },
]

export default sidebar
